### PR TITLE
Bot rev2

### PR DESCRIPTION
**Pull request by agausmann**
I completely rewrote the code to make it more Pythonic in nature, which included many things:
- Separate runtime/library code. I always do my best to separate these two to make the code more reusable.
- Conformity to style conventions. The old code was definitely not compliant to the PEP 8 style guideline, which I believe _everyone_ should review and put into practice.
- Usage of decorators. I used decorators for any of the miscellaneous hooks into the bot (including commands) because it allows further extensibility.
- Project structure. As mentioned before, I have separated our runtime code from the actual library. The bot's core package can be installed locally (and should be before running any main code) by running `./setup.py install` at the command line.
- Other various optimizations and usages of high-level Python functions

### CODE REVIEW

**Comment by agausmann** [comment]
This code will be tested on the ORE channel overnight, and I will check and fix errors in the morning.

**Comment by wgaylord** [comment]
I like this... (I need to actually go from using 2 spaces as tab back to four....)

**Comment by agausmann** [comment]
This is now running in place of the old bot, and will hopefully restart itself if it crashes. All of the output is being logged to be analyzed in 10-ish hours for crashes. Feel free to test the new bot on the ORE channel; it should have all the same functionality as the old one.

**Comment by agausmann** [comment]
After a couple of minor issues, the bot was running perfectly fine. There were no crashes or disconnects overnight, as far as I can see. It seems stable enough to merge.

**Pull request merged**
